ntpServer = input("Enter your NTP server ")
print("\n")
dnsServer = input("Enter your DNS server, if 2nd server is needed separate with space ")
print("\n")
sourceInterface = input("What is the source interface (example G0/0/0, G0/0/1)? ")
print("\n")
encryptionPassword = input("Enter your password for encryption: ") 
print("\n")
providerIP = input("Enter the provider IP address for the PSTN trunk: ")
print("\n")
otgDTG = input("OTG/DTG trunk group: ")
print("\n")
outboundProxy = input("Outbound Proxy Address FQDN: ")
print("\n")
registrarDomain = input("Registrar Domain FQDN: ")
print("\n")
linePort = input("Line Port: (just enter the first part before @) ")
print("\n")
LGW_username = input("Username: ")
print("\n")
LGW_password = input("Password: ")
print("\n")
print("key config-key password-encrypt "+encryptionPassword)
print("password encryption aes")
print("\n")
print("crypto pki trustpoint EmptyTP")
print(" revocation-check none")
print("\n")
print("sip-ua")
print("timers connection establish tls 5")
print("transport tcp tls v1.2")
print("crypto signaling default trustpoint EmptyTP cn-san-validate server")
print("tcp-retry 1000")
print("\n")
print("ip http client source-interface GigabitEthernet0/0/0")
print("crypto pki trustpool import clean url https://www.cisco.com/security/pki/trs/ios_core.p7b")
print("\n")
print("\n")
print("voice service voip")
print("ip address trusted list")
print("ipv4 23.89.0.0 255.255.0.0")
print("ipv4 62.109.192.0 255.255.192.0")
print("ipv4 85.119.56.0 255.255.254.0")
print("ipv4 128.177.14.0 255.255.255.0")
print("ipv4 128.177.36.0 255.255.255.0")
print("ipv4 135.84.168.0 255.255.248.0")
print("ipv4 139.177.64.0 255.255.248.0")
print("ipv4 139.177.72.0 255.255.254.0")
print("ipv4 144.196.0.0 255.255.0.0")
print("ipv4 150.253.128.0 255.255.128.0")
print("ipv4 163.129.0.0 255.255.128.0")
print("ipv4 170.72.0.0 255.255.0.0")
print("ipv4 170.133.128.0 255.255.192.0")
print("ipv4 185.115.196.0 255.255.252.0")
print("ipv4 199.19.196.0 255.255.254.0")
print("ipv4 199.19.199.0 255.255.255.0")
print("ipv4 199.59.64.0 255.255.248.0")
print("mode border-element")
print("media statistics")
print("media bulk-stats") 
print("allow-connections sip to sip")
print("no supplementary-service sip refer")  
print("stun")
print("stun flowdata agent-id 1 boot-count 4")
print("stun flowdata shared-secret 0 "+ encryptionPassword)
print("sip")
print("asymmetric payload full")
print("early-offer forced")  
print("\n")
print("voice class codec 100")
print("codec preference 1 g711ulaw")
print("codec preference 2 g711alaw")
print("\n")
print("voice class stun-usage 100") 
print("stun usage firewall-traversal flowdata")
print("stun usage ice lite")
print("\n")
print("voice class srtp-crypto 100")
print("crypto 1 AES_CM_128_HMAC_SHA1_80")
print("\n")
print("voice class uri 100 sip")
print("pattern dtg="+otgDTG)
print("\n")
print("voice class sip-profiles 100")
print("rule 10 request ANY sip-header SIP-Req-URI modify \"sips:\" \"sip:\"")
print("rule 20 request ANY sip-header To modify \"<sips:\" \"<sip:\"")
print("rule 30 request ANY sip-header From modify \"<sips:\" \"<sip:\"")
print("rule 40 request ANY sip-header Contact modify \"<sips:(.*)>\" \"<sip:\1;transport=tls>\"") 
print("rule 50 response ANY sip-header To modify \"<sips:\" \"<sip:\"")
print("rule 60 response ANY sip-header From modify \"<sips:\" \"<sip:\"")
print("rule 70 response ANY sip-header Contact modify \"<sips:\" \"<sip:\"")
print("rule 80 request ANY sip-header From modify \">\" \";otg="+otgDTG+"\">\"")
print("rule 90 request ANY sip-header P-Asserted-Identity modify \"sips:\" \"sip:\"")
print("\n")
print("voice class tenant 100")
print("registrar dns:"+registrarDomain+"scheme sips expires 240 refresh-ratio 50 tcp tls")
print("credentials number "+linePort+" username "+LGW_username+" password 0 "+LGW_password+" realm BroadWorks")
print("authentication username "+LGW_username+" password 0 "+LGW_password+" realm BroadWorks")
print("authentication username "+LGW_username+" password 0 "+LGW_password+" realm "+registrarDomain)
print("no remote-party-id")
print("sip-server dns:"+registrarDomain)
print("connection-reuse")
print("srtp-crypto 100")
print("session transport tcp tls") 
print("no session refresh")
print("url sips") 
print("error-passthru")
print("rel1xx disable")
print("asserted-id pai") 
print("bind control source-interface "+sourceInterface)
print("bind media source-interface "+sourceInterface)
print("no pass-thru content custom-sdp")
print("sip-profiles 100")
print("outbound-proxy dns:"+outboundProxy)
print("privacy-policy passthru")
print("\n")
print("dial-peer voice 100 voip")
print("description Inbound/Outbound Webex Calling")
print("max-conn 250")
print("destination-pattern BAD.BAD")
print("session protocol sipv2")
print("session target sip-server")
print("incoming uri request 100")
print("voice-class codec 100")
print("dtmf-relay rtp-nte")
print("voice-class stun-usage 100")
print("no voice-class sip localhost")
print("voice-class sip tenant 100")
print("srtp")
print("no vad")
print("\n")
print("voice class uri 200 sip")
print("host ipv4:"+providerIP)
print("\n")
print("dial-peer voice 200 voip")
print("description Inbound/Outbound IP PSTN trunk")
print("destination-pattern BAD.BAD")
print("session protocol sipv2")
print("session target ipv4:"+providerIP)
print("incoming uri via 200")
print("voice-class sip asserted-id pai")
print("voice-class sip bind control source-interface "+sourceInterface) 
print("voice-class sip bind media source-interface  "+sourceInterface) 
print("voice-class codec 100")
print("dtmf-relay rtp-nte") 
print("no vad")
print("\n")
print("voice class dpg 100") 
print("description Route calls to Webex Calling")
print("dial-peer 100") 
print("voice class dpg 200")
print("description Route calls to PSTN") 
print("dial-peer 200")
print("\n")
print("dial-peer voice 100")
print("destination dpg 200")
print("dial-peer voice 200")
print("destination dpg 100")
print("\n")